; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_prodam_garazh_ost=music_data_prodam_garazh_ost
.endif

music_data_prodam_garazh_ost:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Youla
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_prodam_garazh_ost
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env6,@env8,@env0 ; 00 : Drum
	.word @env7,@env6,@env2,@env0 ; 01 : Instrument 1
	.word @env1,@env6,@env9,@env0 ; 02 : Instrument 2

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c6,$7f,$00,$02
@env2:
	.byte $c0,$c0,$c2,$00,$02
@env3:
	.byte $00,$ca,$c7,$c4,$c3,$c2,$c1,$c0,$00,$07
@env4:
	.byte $00,$c0,$b9,$b4,$b3,$b6,$bc,$c4,$ca,$cd,$cc,$c7,$00,$01
@env5:
	.byte $00,$cf,$7f,$00,$02
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $00,$c7,$7f,$00,$02
@env8:
	.byte $7f,$00,$00
@env9:
	.byte $c1,$7f,$00,$00
@env10:
	.byte $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01
@env11:
	.byte $00,$c0,$b5,$b0,$b5,$c0,$cb,$d0,$cb,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0c,$0f,$20 ; 00 BassDrum (Pitch:15)
	.byte $03+.lobyte(FAMISTUDIO_DPCM_PTR),$30,$0f,$20 ; 01 Snare (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $48, .lobyte(@env10), .hibyte(@env10), $d5, $82
@song0ref10:
	.byte $20, $9f, $00, $cd, $1f, $a5, $00, $cd, $47, $cf, $20, $a5, $1f, $a5, $00, $a5, $1f, $a5, $00, $cd, $47, $48, .lobyte(@env10)
	.byte .hibyte(@env10), $d5
	.byte $41, $14
	.word @song0ref10
	.byte $41, $14
	.word @song0ref10
	.byte $41, $14
	.word @song0ref10
	.byte $41, $14
	.word @song0ref10
	.byte $41, $14
	.word @song0ref10
	.byte $41, $14
	.word @song0ref10
	.byte $41, $13
	.word @song0ref10
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $48, .lobyte(@env4), .hibyte(@env4), $cf, $82
@song0ref81:
	.byte $18, $a5, $00, $cd, $17, $a5, $00, $cd, $cf, $18, $a5, $17, $a5, $00, $a5, $17, $a5, $00, $cd, $48, .lobyte(@env4)
	.byte .hibyte(@env4), $cf
	.byte $41, $14
	.word @song0ref81
	.byte $41, $14
	.word @song0ref81
	.byte $41, $13
	.word @song0ref81
	.byte $48, .lobyte(@env4), .hibyte(@env4), $84, $14, $a5, $00, $a5, $18, $a5, $14, $a5, $13, $a5, $00, $f5, $14, $a5, $00
	.byte $a5, $18, $a5, $14, $a5, $13, $a5, $14, $a5, $00, $cd, $14, $a5, $00, $a5, $18, $a5, $14, $91, $13, $91, $14, $91, $00
	.byte $91, $18, $a5, $00, $a5, $13, $91, $13, $91, $14, $a5, $13, $a5, $18, $a5, $16, $a5, $00, $a5, $16, $a5, $14, $a5, $13
	.byte $a5, $48, .lobyte(@env4), .hibyte(@env4), $14, $a5, $00, $a5, $18, $a5, $00, $cd, $14, $a5, $00, $cd, $cf, $82, $18
	.byte $a5, $17, $a5, $00, $a5, $17, $a5, $00, $cd, $48, .lobyte(@env4), .hibyte(@env4), $cf
	.byte $41, $13
	.word @song0ref81
@song0ref215:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $48, .lobyte(@env11), .hibyte(@env11), $82
@song0ref235:
	.byte $14, $cd, $00, $a5, $13, $cd, $00, $f5, $14, $cd, $00, $a5, $13, $cd, $00, $a5, $0c, $a5, $0d, $a5, $48, .lobyte(@env11)
	.byte .hibyte(@env11)
	.byte $41, $14
	.word @song0ref235
	.byte $48, .lobyte(@env11), .hibyte(@env11)
	.byte $41, $14
	.word @song0ref235
	.byte $48, .lobyte(@env11), .hibyte(@env11)
	.byte $41, $14
	.word @song0ref235
	.byte $48, .lobyte(@env11), .hibyte(@env11)
	.byte $41, $14
	.word @song0ref235
	.byte $48, .lobyte(@env11), .hibyte(@env11)
	.byte $41, $14
	.word @song0ref235
	.byte $48, .lobyte(@env11), .hibyte(@env11)
	.byte $41, $14
	.word @song0ref235
	.byte $48, .lobyte(@env11), .hibyte(@env11)
	.byte $41, $14
	.word @song0ref235
	.byte $48, .lobyte(@env11), .hibyte(@env11)
	.byte $41, $14
	.word @song0ref235
	.byte $48, .lobyte(@env11), .hibyte(@env11)
	.byte $41, $14
	.word @song0ref235
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $0c
	.word @song0ref215
@song0ref316:
	.byte $93, $80
@song0ref318:
	.byte $20, $91, $20, $91, $20, $91, $82, $19, $91, $00, $cd, $80, $20, $91, $82, $19, $91, $00, $a5, $80, $20, $91, $00, $a5
	.byte $93
	.byte $41, $15
	.word @song0ref318
	.byte $41, $15
	.word @song0ref318
@song0ref349:
	.byte $20, $91, $20, $91, $20, $91, $82, $19, $91, $00, $ff, $89, $19, $91, $00, $91, $19, $91, $19, $8f, $00
	.byte $41, $16
	.word @song0ref316
	.byte $41, $15
	.word @song0ref318
	.byte $41, $15
	.word @song0ref318
	.byte $41, $14
	.word @song0ref349
	.byte $41, $16
	.word @song0ref316
	.byte $41, $15
	.word @song0ref318
	.byte $41, $15
	.word @song0ref318
	.byte $41, $14
	.word @song0ref349
	.byte $41, $16
	.word @song0ref316
	.byte $41, $15
	.word @song0ref318
	.byte $41, $15
	.word @song0ref318
	.byte $41, $14
	.word @song0ref349
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $9f, $01, $91, $00, $b9, $01, $91, $00
@song0ref428:
	.byte $91, $01, $91, $01
@song0ref432:
	.byte $91, $01, $91, $00, $b9, $02, $91, $00, $91, $01, $91, $01, $91, $01, $91, $00, $91, $02, $91, $01, $91, $00, $a5, $01
	.byte $91, $00, $91, $01, $91, $00, $b9, $02, $91, $00, $91, $01, $91, $00, $91, $01, $91, $00, $91, $02, $91, $01, $91, $00
	.byte $91, $01
	.byte $41, $2f
	.word @song0ref428
	.byte $01, $91, $00, $91, $02, $91, $00, $91, $02, $91, $02
	.byte $41, $32
	.word @song0ref432
	.byte $41, $2f
	.word @song0ref428
	.byte $01, $91, $00, $91, $02, $91, $00, $91, $02, $91, $02
	.byte $41, $32
	.word @song0ref432
	.byte $41, $2f
	.word @song0ref428
	.byte $01, $91, $00, $91, $02, $91, $00, $91, $02, $91, $02
	.byte $41, $32
	.word @song0ref432
	.byte $41, $2f
	.word @song0ref428
	.byte $01, $91, $00, $91, $02, $91, $00, $91, $02, $91, $02, $91, $42
	.word @song0ch4loop
