; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Song 1
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80, $2d, $cd, $24, $cd, $28, $cd, $2b, $cd, $47, $00, $ff
	.byte $ff, $bd
@song0ref19:
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf
	.byte $47, $ff, $ff, $bf
	.byte $41, $15
	.word @song0ref19
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80, $25, $cd, $2b, $cd, $21
@song0ref60:
	.byte $cd, $31
@song0ref62:
	.byte $cd
@song0ref63:
	.byte $00, $ff, $ff, $bd
@song0ref67:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $15
	.word @song0ref67
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $24, $cd, $2d, $cd, $1f, $cd, $2a
	.byte $41, $1a
	.word @song0ref62
	.byte $41, $15
	.word @song0ref67
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80, $32, $cd, $2e, $cd, $38
	.byte $41, $1c
	.word @song0ref60
	.byte $41, $15
	.word @song0ref67
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $ff, $bf
	.byte $41, $19
	.word @song0ref63
	.byte $41, $15
	.word @song0ref67
	.byte $42
	.word @song0ch4loop
